export interface Joke {
  id: number;
  dbms: 'sqlserver' | 'oracle' | 'postgresql' | 'mongodb';
  text: string;
}

export const JOKES: Joke[] = [
  // --- SQL Server (40 jokes) ---
  { id: 1, dbms: 'sqlserver', text: "Why did the SQL Server query go to therapy? It had too many nested loops and felt completely blocked." },
  { id: 2, dbms: 'sqlserver', text: "How many SQL Server DBAs does it take to change a lightbulb? Three. One to drop it, one to recreate it, and one to restore from backup." },
  { id: 3, dbms: 'sqlserver', text: "SQL Server: 'I have a brand new execution plan!' DBA: 'Is it faster?' SQL Server: 'No, but it is different!'" },
  { id: 4, dbms: 'sqlserver', text: "Why does SQL Server hate hot weather? Because it hates seeing tempdb melt under pressure." },
  { id: 5, dbms: 'sqlserver', text: "Why did the transaction log cross the road? To reach the next backup before filling up the disk." },
  { id: 6, dbms: 'sqlserver', text: "What is a SQL Server DBA's favorite dance move? The deadlock pivot." },
  { id: 7, dbms: 'sqlserver', text: "Why did the index rebuild get cancelled? It was too fragmented to make up its mind." },
  { id: 8, dbms: 'sqlserver', text: "How do you know a query is hitting a columnstore index? It finishes before you can take a sip of coffee." },
  { id: 9, dbms: 'sqlserver', text: "Why did the AlwaysOn Availability Group replica break up? It couldn't handle the commitment latency." },
  { id: 10, dbms: 'sqlserver', text: "Why did the developer write a cursor? They wanted to take a scenic route through the table, one row at a time." },
  { id: 11, dbms: 'sqlserver', text: "What's the difference between a developer and a SQL Server DBA? The developer thinks a deadlock is a band name." },
  { id: 12, dbms: 'sqlserver', text: "Why did the SQL Server agent get fired? It missed its scheduled jobs because it was stuck in a loop." },
  { id: 13, dbms: 'sqlserver', text: "Why did the database administrator get kicked out of the concert? They kept trying to kill the active sessions." },
  { id: 14, dbms: 'sqlserver', text: "Why does SSMS have a 'new query' button? Because the old queries are too depressing to look at." },
  { id: 15, dbms: 'sqlserver', text: "Why did the table go to the gym? It wanted to reduce its page allocation and get compressed." },
  { id: 16, dbms: 'sqlserver', text: "Why did the SQL Server query optimizer get promoted? It found a parallel path to success." },
  { id: 17, dbms: 'sqlserver', text: "What does SQL Server do when it gets tired? It takes a page latch." },
  { id: 18, dbms: 'sqlserver', text: "Why did the database restore fail? Because the backup was taken on a Friday at 4:59 PM." },
  { id: 19, dbms: 'sqlserver', text: "Why do SQL Server developers love nested views? They enjoy playing database inception." },
  { id: 20, dbms: 'sqlserver', text: "What is a SQL Server's favorite music genre? Lock and Roll." },
  { id: 21, dbms: 'sqlserver', text: "Why did the SQL Server query run so slowly? It got lost in the database schema search." },
  { id: 22, dbms: 'sqlserver', text: "Why did the AlwaysOn listener go to the doctor? It had a bad connection." },
  { id: 23, dbms: 'sqlserver', text: "Why did the database developer get a ticket? They were caught speeding through a clustered index scan." },
  { id: 24, dbms: 'sqlserver', text: "Why did the column get defensive? It was told it wasn't unique enough." },
  { id: 25, dbms: 'sqlserver', text: "What is a database's favorite movie? The Lord of the Rings: The Fellowship of the Schema." },
  { id: 26, dbms: 'sqlserver', text: "Why did the SQL Server DBA refuse to play hide and seek? Because good luck hiding when sp_whoisactive is running." },
  { id: 27, dbms: 'sqlserver', text: "Why did the database constraint fail? It had too many boundary issues." },
  { id: 28, dbms: 'sqlserver', text: "Why did the query join the gym? It wanted to optimize its hash joins." },
  { id: 29, dbms: 'sqlserver', text: "Why did the database table cross the road? To join the other side." },
  { id: 30, dbms: 'sqlserver', text: "Why did the SQL Server query optimizer wear glasses? To see the index statistics more clearly." },
  { id: 31, dbms: 'sqlserver', text: "Why did the transaction log get so emotional? It kept remembering everything that happened." },
  { id: 32, dbms: 'sqlserver', text: "Why did the database file get compressed? It was taking up too much personal space." },
  { id: 33, dbms: 'sqlserver', text: "Why did the query get rejected by the partition? It didn't fit the boundary criteria." },
  { id: 34, dbms: 'sqlserver', text: "Why did the SQL Server query go to the party? To meet some new columns." },
  { id: 35, dbms: 'sqlserver', text: "Why did the database table have a headache? It had too many primary keys trying to lead." },
  { id: 36, dbms: 'sqlserver', text: "Why did the database administrator get a citation? They were caught leaving transaction logs unbacked." },
  { id: 37, dbms: 'sqlserver', text: "Why did the SQL Server agent job get depressed? It kept running into failures every hour." },
  { id: 38, dbms: 'sqlserver', text: "Why did the database query fail the exam? It forgot to join the correct tables." },
  { id: 39, dbms: 'sqlserver', text: "Why did the AlwaysOn cluster go to the gym? To improve its failover capabilities." },
  { id: 40, dbms: 'sqlserver', text: "Why did the database developer get a cold? They left too many connections open to the draft." },

  // --- Oracle (40 jokes) ---
  { id: 41, dbms: 'oracle', text: "How do you know an Oracle DBA is happy? They only complain about licensing twice a day." },
  { id: 42, dbms: 'oracle', text: "What is an Oracle DBA's favorite error? ORA-00600: Internal error code, arguments: [Good luck, you will need it]." },
  { id: 43, dbms: 'oracle', text: "Why did the DBA write an Oracle package? They wanted to wrap their problems in a neat little body." },
  { id: 44, dbms: 'oracle', text: "What does Larry Ellison do when he buys a new yacht? He names it 'ORA-00942: Table or view does not exist'." },
  { id: 45, dbms: 'oracle', text: "Why did the Oracle database crash? It ran out of system tablespace because someone tried to store the licensing manual." },
  { id: 46, dbms: 'oracle', text: "Why do Oracle DBAs love AWR reports? They are great bedtime stories for finding high-load SQL." },
  { id: 47, dbms: 'oracle', text: "Why did the database tablespace go to court? It was accused of illegal auto-extend operations." },
  { id: 48, dbms: 'oracle', text: "Why did the Oracle RAC cluster fail? One node decided it wanted to be a sole proprietor." },
  { id: 49, dbms: 'oracle', text: "Why did the DBA use impdp? Because they wanted to import their problems from another database." },
  { id: 50, dbms: 'oracle', text: "Why do Oracle queries love v$session? It is the ultimate social network for active connections." },
  { id: 51, dbms: 'oracle', text: "Why did the Oracle DBA get a boat? To navigate the sea of license audits." },
  { id: 52, dbms: 'oracle', text: "Why did the redo log switch get cancelled? It was too archived to make a clean break." },
  { id: 53, dbms: 'oracle', text: "Why did the Oracle database go to school? To learn how to read tablespaces properly." },
  { id: 54, dbms: 'oracle', text: "Why did the DBA refuse to play poker with Oracle? Oracle always counts the cards twice for licensing purposes." },
  { id: 55, dbms: 'oracle', text: "Why did the Oracle sequence get promoted? It was always going up, one step at a time." },
  { id: 56, dbms: 'oracle', text: "Why did the index get deleted? It was accused of taking up space without adding any value." },
  { id: 57, dbms: 'oracle', text: "Why did the Oracle database have a bad dream? It dreamed it was being replaced by a spreadsheet." },
  { id: 58, dbms: 'oracle', text: "Why did the DBA get a headache from tnsnames.ora? It had too many parentheses to count." },
  { id: 59, dbms: 'oracle', text: "Why did the Oracle database go to the therapist? It had severe memory SGA leaks." },
  { id: 60, dbms: 'oracle', text: "Why do Oracle DBAs love RMAN? It is the only backup manager that actually returns a clean exit code." },
  { id: 61, dbms: 'oracle', text: "Why did the query optimizer choose a full table scan? It was too lazy to look for the index." },
  { id: 62, dbms: 'oracle', text: "Why did the Oracle developer use a trigger? They wanted to cause unexpected consequences." },
  { id: 63, dbms: 'oracle', text: "Why did the database administrator get a citation? They were caught running expdp without a valid directory." },
  { id: 64, dbms: 'oracle', text: "Why did the tablespace run out of space? Because someone tried to store the history of the world in a single VARCHAR2." },
  { id: 65, dbms: 'oracle', text: "Why did the Oracle database get a cold? It was left in the draft of an uncommitted transaction." },
  { id: 66, dbms: 'oracle', text: "Why did the sequence go backward? It got confused by a cycle instruction." },
  { id: 67, dbms: 'oracle', text: "Why did the Oracle cluster lose synchronization? It decided to failover to a different timezone." },
  { id: 68, dbms: 'oracle', text: "Why did the DBA get a ticket? They were caught speeding through a nested loop join." },
  { id: 69, dbms: 'oracle', text: "Why did the Oracle index rebuild fail? It got blocked by a transaction that was started in 1999." },
  { id: 70, dbms: 'oracle', text: "Why did the database developer get a ticket? They were caught leaving connections open to the internet." },
  { id: 71, dbms: 'oracle', text: "Why did the sequence get depressed? It realized it could never go back to zero." },
  { id: 72, dbms: 'oracle', text: "Why did the tablespace go to the gym? It wanted to increase its extent allocation." },
  { id: 73, dbms: 'oracle', text: "Why did the Oracle database get a citation? It was caught running without a valid license file." },
  { id: 74, dbms: 'oracle', text: "Why did the DBA get a ticket? They were caught running impdp with the force option." },
  { id: 75, dbms: 'oracle', text: "Why did the Oracle database go to the doctor? It was suffering from severe memory fragmentation." },
  { id: 76, dbms: 'oracle', text: "Why did the DBA refuse to play hide and seek? Because Larry Ellison is always watching for license audits." },
  { id: 77, dbms: 'oracle', text: "Why did the sequence get promoted? It was always incrementing." },
  { id: 78, dbms: 'oracle', text: "Why did the database tablespace go to court? It auto-extended without permission." },
  { id: 79, dbms: 'oracle', text: "Why did the Oracle RAC fail? The interconnect got disconnected by a vacuum cleaner." },
  { id: 80, dbms: 'oracle', text: "Why did the database query fail? It forgot to use the correct join clause." },

  // --- PostgreSQL (10 jokes) ---
  { id: 81, dbms: 'postgresql', text: "Why did the PostgreSQL database feel so clean? Because it was VACUUMed twice today." },
  { id: 82, dbms: 'postgresql', text: "Why do PostgreSQL developers love MVCC? They enjoy having multiple versions of the truth." },
  { id: 83, dbms: 'postgresql', text: "Why did the PostgreSQL elephant mascot get promoted? It had an excellent memory for queries." },
  { id: 84, dbms: 'postgresql', text: "Why did the WAL log get so big? It kept writing down every single keystroke." },
  { id: 85, dbms: 'postgresql', text: "Why did pgAdmin crash? Because it was open for more than 10 minutes." },
  { id: 86, dbms: 'postgresql', text: "Why do PostgreSQL queries run faster on Linux? Because Windows is too busy updating." },
  { id: 87, dbms: 'postgresql', text: "Why did the PostgreSQL developer get a ticket? They were caught speeding through a serial scan." },
  { id: 88, dbms: 'postgresql', text: "Why did the PostgreSQL index get deleted? It wasn't being used by the query planner." },
  { id: 89, dbms: 'postgresql', text: "Why did the PostgreSQL sequence fail? It ran out of numbers." },
  { id: 90, dbms: 'postgresql', text: "Why did the PostgreSQL database go to the doctor? It had a bad connection pool." },

  // --- MongoDB (10 jokes) ---
  { id: 91, dbms: 'mongodb', text: "Why did the MongoDB developer get lost? Because they couldn't find any joins." },
  { id: 92, dbms: 'mongodb', text: "Why do MongoDB developers love schema-less databases? They enjoy the freedom of writing whatever they want." },
  { id: 93, dbms: 'mongodb', text: "Why did the MongoDB database crash? It tried to shard a collection by a field that didn't exist." },
  { id: 94, dbms: 'mongodb', text: "Why did the MongoDB query fail? It couldn't find the document." },
  { id: 95, dbms: 'mongodb', text: "Why do MongoDB developers hate SQL? Because SQL has too many relations." },
  { id: 96, dbms: 'mongodb', text: "Why did the MongoDB database go to the doctor? It was suffering from collection bloat." },
  { id: 97, dbms: 'mongodb', text: "Why did the MongoDB shard key fail? It wasn't unique enough." },
  { id: 98, dbms: 'mongodb', text: "Why did the MongoDB database get a cold? It was left in the draft of a replica set failover." },
  { id: 99, dbms: 'mongodb', text: "Why did the MongoDB developer get a ticket? They were caught speeding through a collection scan." },
  { id: 100, dbms: 'mongodb', text: "Why did the MongoDB sequence fail? It didn't have one." }
];
